# name: CI-CD

on: push

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    env:
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Install DVC
        run: pip install "dvc"

      # OPTIONAL: If your `.dvc` files or `dvc.lock` track local data, but the data is already committed to Git
      # and small in size, you can skip dvc pull. Otherwise, you may simulate local data setup.

      # - name: DVC Pull (if needed)
      #   run: |
      #     dvc pull
      - name: Install Testing Tools (pytest)
        run: pip install pytest

      - name: Install dagshub with token support
        run: pip install dagshub>=0.3.12




      - name: Test Model Registry
        run: |
          export DAGSHUB_USER_TOKEN="bc97bd38dfc84d2637b9a9ead8374a6d30bd0be2"
          pytest tests/test_model_registry.py

      - name: Test Model Performance
        run: |
          export DAGSHUB_USER_TOKEN="bc97bd38dfc84d2637b9a9ead8374a6d30bd0be2"
          pytest tests/test_model_perf.py

      - name: Promote Model
        if: success()
        run: |
          export DAGSHUB_USER_TOKEN="bc97bd38dfc84d2637b9a9ead8374a6d30bd0be2"
          python scripts/promote_model_to_prod.py
